### ISSUE TITLE
Bug NoImage on banner

### ISSUE THREAD

**Issue by mhtranbn** [bryx-inc/BRYXBanner#46] opened 2016-07-11 15:59 UTC
Hi @adambinsz, you are anesome! , please support for me, why not show image on baner.?  100000000000 thank for this greate job!

**Comment by zntfdr** [comment] 2016-08-14 05:13
Duplicate of #45 .

Please don't open a new issue if there's one about this already.

**Closed as completed** 2016-08-21 01:17 UTC
