### ISSUE TITLE
*** Skipped building BRYXBanner due to the error:

### ISSUE THREAD

**Issue by NithyaVenkat** [bryx-inc/BRYXBanner#60] opened 2016-09-20 10:55 UTC
**\* Fetching BRYXBanner
**\* Checking out BRYXBanner at "0.7.0"
**\* xcodebuild output can be found in /var/folders/nc/jrryg2gs72vg47hjnbsyhn700000gn/T/carthage-xcodebuild.HJxQDz.log
**\* Skipped building BRYXBanner due to the error:
Dependency "BRYXBanner" has no shared framework scheme

ran in to this error whicle upating the latest for iOS 10?

**Comment by makoni** [comment] 2016-09-22 10:40
I've fixed it in #61 
You can use my fork until PR will be merged: https://github.com/makoni/BRYXBanner

**Comment by harlanhaskins** [comment] 2016-09-22 11:55
PR merged. Sorry for the inconvenience! Try version 0.7.1.

**Comment by harlanhaskins** [comment] 2016-09-22 11:55
Closing as a dupe of #59.

**Closed as completed by harlanhaskins** 2016-09-22 11:55 UTC
