### ISSUE TITLE
Calling show from obj-c, Swift-2.0 branch

### ISSUE THREAD

**Issue by aminiz** [bryx-inc/BRYXBanner#15] opened 2015-08-19 00:13 UTC
The method is not available. It is not shown in the generated BRYXBanner-Swift.h
I am temporarily working around this by using the following class

```
import UIKit
import BRYXBanner

class MPTBanner: Banner {
    override func show(duration duration: NSTimeInterval?) {
        super.show(duration: duration)
    }

    func show() {
        super.show(duration: 3.0)
    }
}
```

**Comment by harlanhaskins** [comment] 2015-08-20 19:31
Oof. Yeah, this isn't great. It's probably because of default arguments in Swift.

**Comment by harlanhaskins** [comment] 2015-09-05 21:11
Duplicate of #18

**Closed as completed by harlanhaskins** 2015-09-05 21:11 UTC
